import type {
  Family,
  FundingAccount,
  Program,
  Registration,
  Activity,
  Transaction,
  CheckInLocation,
  ExperienceVenue,
  CheckInRecord,
  SchoolProgram,
} from './types';

export const family: Family = {
  id: 'fam-001',
  name: 'Garcia',
  email: 'maria.garcia@email.com',
  phone: '(720) 555-0147',
  address: {
    street: '2847 Welton Street',
    city: 'Denver',
    state: 'CO',
    zip: '80205',
    neighborhood: 'Five Points',
    coordinates: { lat: 39.7549, lng: -104.9772 },
  },
  children: [
    {
      id: 'child-001',
      name: 'Sofia',
      age: 16,
      birthDate: '2009-04-12',
      avatar: '👧',
      eligiblePrograms: ['prog-002', 'prog-005', 'prog-007', 'prog-009', 'prog-010'],
    },
    {
      id: 'child-002',
      name: 'Diego',
      age: 7,
      birthDate: '2018-09-23',
      avatar: '👦',
      eligiblePrograms: ['prog-001', 'prog-003', 'prog-004', 'prog-006', 'prog-008'],
    },
  ],
  denverCardNumber: 'MDY-2024-847291',
};

export const fundingAccounts: FundingAccount[] = [
  {
    id: 'fund-001',
    name: 'My Spark',
    nameEs: 'Mi Chispa',
    type: 'scholarship',
    balance: 750,
    maxBalance: 1000,
    color: '#662E93',
    description: 'City of Denver scholarship for youth enrichment activities',
    descriptionEs: 'Beca de la Ciudad de Denver para actividades de enriquecimiento juvenil',
    eligibleCategories: ['sports', 'stem', 'arts', 'outdoor', 'academic', 'music', 'dance', 'life-skills'],
    expirationDate: '2025-12-31',
  },
  {
    id: 'fund-002',
    name: 'DPS Activity Grant',
    nameEs: 'Beca de Actividades DPS',
    type: 'grant',
    balance: 300,
    maxBalance: 500,
    color: '#0077C8',
    description: 'Denver Public Schools grant for after-school activities',
    descriptionEs: 'Beca de las Escuelas Publicas de Denver para actividades extracurriculares',
    eligibleCategories: ['stem', 'arts', 'academic', 'music'],
    expirationDate: '2025-08-31',
  },
  {
    id: 'fund-003',
    name: 'CCCAP',
    nameEs: 'CCCAP',
    type: 'subsidy',
    balance: 1200,
    maxBalance: 2000,
    color: '#00843D',
    description: 'Colorado Child Care Assistance Program for qualifying families',
    descriptionEs: 'Programa de Asistencia para el Cuidado Infantil de Colorado para familias que califican',
    eligibleCategories: ['sports', 'stem', 'outdoor', 'academic', 'life-skills'],
    expirationDate: '2025-06-30',
  },
];

export const programs: Program[] = [
  {
    id: 'prog-001',
    name: 'Soccer Stars',
    nameEs: 'Estrellas del Futbol',
    provider: 'Denver Parks & Recreation',
    providerEs: 'Parques y Recreacion de Denver',
    category: 'sports',
    description: 'Youth soccer program teaching fundamentals, teamwork, and sportsmanship. All skill levels welcome.',
    descriptionEs: 'Programa de futbol juvenil que ensena fundamentos, trabajo en equipo y deportividad. Todos los niveles son bienvenidos.',
    ageRange: { min: 6, max: 12 },
    schedule: {
      days: ['Tuesday', 'Thursday'],
      startTime: '4:00 PM',
      endTime: '5:30 PM',
      startDate: '2025-01-14',
      endDate: '2025-03-20',
      sessionLength: '10 weeks',
    },
    location: {
      name: 'Ruby Hill Park',
      address: '1200 W Florida Ave, Denver, CO 80223',
      neighborhood: 'Ruby Hill',
      coordinates: { lat: 39.6875, lng: -105.0003 },
    },
    cost: 150,
    spotsTotal: 24,
    spotsAvailable: 8,
    acceptedFunding: ['fund-001', 'fund-003'],
    image: '/images/soccer.jpg',
    tags: ['soccer', 'team sports', 'outdoor', 'fitness'],
  },
  {
    id: 'prog-002',
    name: 'Code Explorers',
    nameEs: 'Exploradores de Codigo',
    provider: 'Denver STEM Alliance',
    providerEs: 'Alianza STEM de Denver',
    category: 'stem',
    description: 'Introduction to coding with Scratch and Python. Build games, animations, and creative projects.',
    descriptionEs: 'Introduccion a la programacion con Scratch y Python. Crea juegos, animaciones y proyectos creativos.',
    ageRange: { min: 8, max: 17 },
    schedule: {
      days: ['Monday', 'Wednesday'],
      startTime: '3:30 PM',
      endTime: '5:00 PM',
      startDate: '2025-01-13',
      endDate: '2025-03-19',
      sessionLength: '10 weeks',
    },
    location: {
      name: 'Blair-Caldwell African American Research Library',
      address: '2401 Welton St, Denver, CO 80205',
      neighborhood: 'Five Points',
      coordinates: { lat: 39.7544, lng: -104.9789 },
    },
    cost: 200,
    spotsTotal: 16,
    spotsAvailable: 3,
    acceptedFunding: ['fund-001', 'fund-002', 'fund-003'],
    image: '/images/coding.jpg',
    tags: ['coding', 'technology', 'computer science', 'Scratch', 'Python'],
  },
  {
    id: 'prog-003',
    name: 'Youth Art Studio',
    nameEs: 'Estudio de Arte Juvenil',
    provider: 'Denver Arts Council',
    providerEs: 'Consejo de Artes de Denver',
    category: 'arts',
    description: 'Mixed-media art exploration including painting, sculpture, and digital art. Express your creativity!',
    descriptionEs: 'Exploracion artistica de medios mixtos incluyendo pintura, escultura y arte digital. Expresa tu creatividad!',
    ageRange: { min: 5, max: 13 },
    schedule: {
      days: ['Saturday'],
      startTime: '10:00 AM',
      endTime: '12:00 PM',
      startDate: '2025-01-18',
      endDate: '2025-03-22',
      sessionLength: '10 weeks',
    },
    location: {
      name: 'McNichols Civic Center Building',
      address: '144 W Colfax Ave, Denver, CO 80202',
      neighborhood: 'Civic Center',
      coordinates: { lat: 39.7392, lng: -104.9847 },
    },
    cost: 175,
    spotsTotal: 20,
    spotsAvailable: 12,
    acceptedFunding: ['fund-001', 'fund-002'],
    image: '/images/art.jpg',
    tags: ['art', 'painting', 'sculpture', 'creative', 'mixed media'],
  },
  {
    id: 'prog-004',
    name: 'Nature Explorers',
    nameEs: 'Exploradores de la Naturaleza',
    provider: 'Denver Audubon Society',
    providerEs: 'Sociedad Audubon de Denver',
    category: 'outdoor',
    description: 'Outdoor education program exploring Denver parks, wildlife, and ecosystems. Includes hiking and nature journaling.',
    descriptionEs: 'Programa de educacion al aire libre explorando parques, vida silvestre y ecosistemas de Denver. Incluye caminatas y diario de naturaleza.',
    ageRange: { min: 6, max: 11 },
    schedule: {
      days: ['Saturday'],
      startTime: '9:00 AM',
      endTime: '12:00 PM',
      startDate: '2025-02-01',
      endDate: '2025-04-05',
      sessionLength: '9 weeks',
    },
    location: {
      name: 'City Park',
      address: '2001 Colorado Blvd, Denver, CO 80205',
      neighborhood: 'City Park',
      coordinates: { lat: 39.7475, lng: -104.9531 },
    },
    cost: 120,
    spotsTotal: 15,
    spotsAvailable: 6,
    acceptedFunding: ['fund-001', 'fund-003'],
    image: '/images/nature.jpg',
    tags: ['nature', 'hiking', 'wildlife', 'ecology', 'outdoor education'],
  },
  {
    id: 'prog-005',
    name: 'Basketball Academy',
    nameEs: 'Academia de Basquetbol',
    provider: 'Denver Nuggets Youth Foundation',
    providerEs: 'Fundacion Juvenil de los Denver Nuggets',
    category: 'sports',
    description: 'Skills development program with Nuggets coaches. Learn basketball fundamentals and game strategy.',
    descriptionEs: 'Programa de desarrollo de habilidades con entrenadores de los Nuggets. Aprende fundamentos y estrategia de basquetbol.',
    ageRange: { min: 8, max: 17 },
    schedule: {
      days: ['Monday', 'Wednesday', 'Friday'],
      startTime: '4:00 PM',
      endTime: '5:30 PM',
      startDate: '2025-01-06',
      endDate: '2025-02-28',
      sessionLength: '8 weeks',
    },
    location: {
      name: 'Hiawatha Davis Recreation Center',
      address: '3334 Holly St, Denver, CO 80207',
      neighborhood: 'Northeast Park Hill',
      coordinates: { lat: 39.7621, lng: -104.9269 },
    },
    cost: 180,
    spotsTotal: 20,
    spotsAvailable: 0,
    acceptedFunding: ['fund-001', 'fund-003'],
    image: '/images/basketball.jpg',
    tags: ['basketball', 'team sports', 'fitness', 'Nuggets'],
  },
  {
    id: 'prog-006',
    name: 'Music Makers',
    nameEs: 'Creadores de Musica',
    provider: 'Colorado Symphony Education',
    providerEs: 'Educacion de la Sinfonia de Colorado',
    category: 'music',
    description: 'Learn to play an instrument! Choose from violin, piano, or guitar. Instruments provided.',
    descriptionEs: 'Aprende a tocar un instrumento! Elige entre violin, piano o guitarra. Se proporcionan instrumentos.',
    ageRange: { min: 6, max: 12 },
    schedule: {
      days: ['Wednesday'],
      startTime: '4:00 PM',
      endTime: '5:30 PM',
      startDate: '2025-01-15',
      endDate: '2025-04-02',
      sessionLength: '12 weeks',
    },
    location: {
      name: 'Boettcher Concert Hall',
      address: '1000 14th St, Denver, CO 80202',
      neighborhood: 'Downtown',
      coordinates: { lat: 39.7437, lng: -104.9962 },
    },
    cost: 250,
    spotsTotal: 12,
    spotsAvailable: 2,
    acceptedFunding: ['fund-001', 'fund-002'],
    image: '/images/music.jpg',
    tags: ['music', 'instrument', 'violin', 'piano', 'guitar', 'symphony'],
  },
  {
    id: 'prog-007',
    name: 'Robotics Club',
    nameEs: 'Club de Robotica',
    provider: 'Denver STEM Alliance',
    providerEs: 'Alianza STEM de Denver',
    category: 'stem',
    description: 'Build and program robots using LEGO Mindstorms and Arduino. Prepare for regional competitions!',
    descriptionEs: 'Construye y programa robots usando LEGO Mindstorms y Arduino. Preparate para competencias regionales!',
    ageRange: { min: 10, max: 17 },
    schedule: {
      days: ['Tuesday', 'Thursday'],
      startTime: '3:30 PM',
      endTime: '5:30 PM',
      startDate: '2025-01-14',
      endDate: '2025-03-20',
      sessionLength: '10 weeks',
    },
    location: {
      name: 'Denver Museum of Nature & Science',
      address: '2001 Colorado Blvd, Denver, CO 80205',
      neighborhood: 'City Park',
      coordinates: { lat: 39.7475, lng: -104.9425 },
    },
    cost: 225,
    spotsTotal: 14,
    spotsAvailable: 5,
    acceptedFunding: ['fund-001', 'fund-002', 'fund-003'],
    image: '/images/robotics.jpg',
    tags: ['robotics', 'LEGO', 'Arduino', 'engineering', 'competition'],
  },
  {
    id: 'prog-008',
    name: 'Creative Dance',
    nameEs: 'Danza Creativa',
    provider: 'Cleo Parker Robinson Dance',
    category: 'dance',
    description: 'Explore movement through creative dance, hip-hop, and cultural dance traditions. All levels welcome.',
    descriptionEs: 'Explora el movimiento a traves de danza creativa, hip-hop y tradiciones culturales de baile. Todos los niveles son bienvenidos.',
    ageRange: { min: 5, max: 12 },
    schedule: {
      days: ['Friday'],
      startTime: '4:00 PM',
      endTime: '5:30 PM',
      startDate: '2025-01-17',
      endDate: '2025-03-21',
      sessionLength: '10 weeks',
    },
    location: {
      name: 'Cleo Parker Robinson Dance Theatre',
      address: '119 Park Ave W, Denver, CO 80205',
      neighborhood: 'Five Points',
      coordinates: { lat: 39.7527, lng: -104.9788 },
    },
    cost: 160,
    spotsTotal: 18,
    spotsAvailable: 10,
    acceptedFunding: ['fund-001'],
    image: '/images/dance.jpg',
    tags: ['dance', 'hip-hop', 'creative movement', 'cultural dance'],
  },
  {
    id: 'prog-009',
    name: 'Youth Workforce Readiness',
    nameEs: 'Preparacion Laboral Juvenil',
    provider: 'Denver Economic Development',
    providerEs: 'Desarrollo Economico de Denver',
    category: 'life-skills',
    description: 'Career exploration, resume building, interview skills, and paid internship placement for teens. Includes financial literacy workshops.',
    descriptionEs: 'Exploracion de carreras, creacion de curriculum, habilidades de entrevista y colocacion de pasantias pagadas para adolescentes. Incluye talleres de educacion financiera.',
    ageRange: { min: 14, max: 18 },
    schedule: {
      days: ['Tuesday', 'Thursday'],
      startTime: '4:00 PM',
      endTime: '6:00 PM',
      startDate: '2025-01-14',
      endDate: '2025-04-03',
      sessionLength: '12 weeks',
    },
    location: {
      name: 'Denver Workforce Center',
      address: '3900 Elati St, Denver, CO 80216',
      neighborhood: 'Globeville',
      coordinates: { lat: 39.7796, lng: -104.9903 },
    },
    cost: 0,
    spotsTotal: 20,
    spotsAvailable: 7,
    acceptedFunding: ['fund-001'],
    image: '/images/workforce.jpg',
    tags: ['career', 'internship', 'resume', 'financial literacy', 'workforce'],
  },
  {
    id: 'prog-010',
    name: 'Teen Leadership Academy',
    nameEs: 'Academia de Liderazgo Juvenil',
    provider: 'Mile High United Way',
    providerEs: 'Mile High United Way',
    category: 'academic',
    description: 'Leadership development, public speaking, community project planning, and college prep. Earn volunteer hours through community service projects.',
    descriptionEs: 'Desarrollo de liderazgo, oratoria, planificacion de proyectos comunitarios y preparacion universitaria. Gana horas de voluntariado a traves de proyectos de servicio comunitario.',
    ageRange: { min: 14, max: 18 },
    schedule: {
      days: ['Saturday'],
      startTime: '10:00 AM',
      endTime: '1:00 PM',
      startDate: '2025-01-18',
      endDate: '2025-04-05',
      sessionLength: '12 weeks',
    },
    location: {
      name: 'Denver Central Library',
      address: '10 W 14th Ave Pkwy, Denver, CO 80204',
      neighborhood: 'Civic Center',
      coordinates: { lat: 39.7377, lng: -104.9882 },
    },
    cost: 100,
    spotsTotal: 15,
    spotsAvailable: 4,
    acceptedFunding: ['fund-001', 'fund-002', 'fund-003'],
    image: '/images/leadership.jpg',
    tags: ['leadership', 'public speaking', 'college prep', 'community service', 'volunteer'],
  },
];

export const registrations: Registration[] = [
  {
    id: 'reg-001',
    programId: 'prog-002',
    childId: 'child-001',
    status: 'confirmed',
    registrationDate: '2024-12-15',
    fundingApplied: [
      { fundingId: 'fund-002', amount: 150 },
      { fundingId: 'fund-001', amount: 50 },
    ],
    totalCost: 200,
    familyCost: 0,
  },
  {
    id: 'reg-002',
    programId: 'prog-009',
    childId: 'child-001',
    status: 'confirmed',
    registrationDate: '2025-01-05',
    fundingApplied: [],
    totalCost: 0,
    familyCost: 0,
  },
  {
    id: 'reg-003',
    programId: 'prog-007',
    childId: 'child-001',
    status: 'confirmed',
    registrationDate: '2025-01-06',
    fundingApplied: [
      { fundingId: 'fund-001', amount: 125 },
      { fundingId: 'fund-002', amount: 100 },
    ],
    totalCost: 225,
    familyCost: 0,
  },
  {
    id: 'reg-004',
    programId: 'prog-001',
    childId: 'child-002',
    status: 'confirmed',
    registrationDate: '2025-01-03',
    fundingApplied: [
      { fundingId: 'fund-001', amount: 100 },
      { fundingId: 'fund-003', amount: 50 },
    ],
    totalCost: 150,
    familyCost: 0,
  },
  {
    id: 'reg-005',
    programId: 'prog-006',
    childId: 'child-002',
    status: 'confirmed',
    registrationDate: '2025-01-04',
    fundingApplied: [
      { fundingId: 'fund-001', amount: 150 },
      { fundingId: 'fund-002', amount: 100 },
    ],
    totalCost: 250,
    familyCost: 0,
  },
];

export const upcomingActivities: Activity[] = [
  {
    id: 'act-001',
    programId: 'prog-009',
    childId: 'child-001',
    date: '2025-01-21',
    startTime: '4:00 PM',
    endTime: '6:00 PM',
  },
  {
    id: 'act-002',
    programId: 'prog-001',
    childId: 'child-002',
    date: '2025-01-21',
    startTime: '4:00 PM',
    endTime: '5:30 PM',
  },
  {
    id: 'act-003',
    programId: 'prog-007',
    childId: 'child-001',
    date: '2025-01-23',
    startTime: '3:30 PM',
    endTime: '5:30 PM',
  },
  {
    id: 'act-004',
    programId: 'prog-006',
    childId: 'child-002',
    date: '2025-01-22',
    startTime: '4:00 PM',
    endTime: '5:30 PM',
  },
  {
    id: 'act-005',
    programId: 'prog-002',
    childId: 'child-001',
    date: '2025-01-27',
    startTime: '3:30 PM',
    endTime: '5:00 PM',
  },
];

export const transactions: Transaction[] = [
  {
    id: 'txn-001',
    date: '2024-12-15',
    programName: 'Code Explorers',
    childName: 'Sofia',
    fundingAccountId: 'fund-002',
    amount: 150,
    type: 'debit',
  },
  {
    id: 'txn-002',
    date: '2024-12-15',
    programName: 'Code Explorers',
    childName: 'Sofia',
    fundingAccountId: 'fund-001',
    amount: 50,
    type: 'debit',
  },
  {
    id: 'txn-003',
    date: '2024-11-01',
    programName: 'My Spark Scholarship',
    childName: '',
    fundingAccountId: 'fund-001',
    amount: 1000,
    type: 'credit',
  },
  {
    id: 'txn-004',
    date: '2024-10-15',
    programName: 'DPS Activity Grant',
    childName: '',
    fundingAccountId: 'fund-002',
    amount: 500,
    type: 'credit',
  },
  {
    id: 'txn-005',
    date: '2024-09-01',
    programName: 'CCCAP Subsidy',
    childName: '',
    fundingAccountId: 'fund-003',
    amount: 2000,
    type: 'credit',
  },
];

export const categoryLabels: Record<string, { en: string; es: string }> = {
  sports: { en: 'Sports', es: 'Deportes' },
  stem: { en: 'STEM', es: 'STEM' },
  arts: { en: 'Arts', es: 'Artes' },
  outdoor: { en: 'Outdoor', es: 'Aire Libre' },
  academic: { en: 'Academic', es: 'Academico' },
  music: { en: 'Music', es: 'Musica' },
  dance: { en: 'Dance', es: 'Baile' },
  'life-skills': { en: 'Life Skills', es: 'Habilidades de Vida' },
};

export const dayLabels: Record<string, { en: string; es: string }> = {
  Monday: { en: 'Monday', es: 'Lunes' },
  Tuesday: { en: 'Tuesday', es: 'Martes' },
  Wednesday: { en: 'Wednesday', es: 'Miercoles' },
  Thursday: { en: 'Thursday', es: 'Jueves' },
  Friday: { en: 'Friday', es: 'Viernes' },
  Saturday: { en: 'Saturday', es: 'Sabado' },
  Sunday: { en: 'Sunday', es: 'Domingo' },
};

export const checkinLocations: CheckInLocation[] = [
  {
    id: 'loc-001',
    name: 'Blair-Caldwell African American Research Library',
    nameEs: 'Biblioteca de Investigacion Afroamericana Blair-Caldwell',
    type: 'library',
    address: '2401 Welton St, Denver, CO 80205',
    neighborhood: 'Five Points',
    coordinates: { lat: 39.7544, lng: -104.9789 },
    hours: 'Mon-Thu 10am-8pm, Fri-Sat 9am-5pm',
    hoursEs: 'Lun-Jue 10am-8pm, Vie-Sab 9am-5pm',
    distance: 0.3,
    programs: ['prog-002'],
  },
  {
    id: 'loc-002',
    name: 'Hiawatha Davis Recreation Center',
    nameEs: 'Centro de Recreacion Hiawatha Davis',
    type: 'rec-center',
    address: '3334 Holly St, Denver, CO 80207',
    neighborhood: 'Northeast Park Hill',
    coordinates: { lat: 39.7621, lng: -104.9269 },
    hours: 'Mon-Fri 6am-9pm, Sat 8am-5pm',
    hoursEs: 'Lun-Vie 6am-9pm, Sab 8am-5pm',
    distance: 2.1,
    programs: ['prog-005'],
  },
  {
    id: 'loc-003',
    name: 'Woodbury Branch Library',
    nameEs: 'Biblioteca Sucursal Woodbury',
    type: 'library',
    address: '3265 Federal Blvd, Denver, CO 80211',
    neighborhood: 'Highland',
    coordinates: { lat: 39.7589, lng: -105.0244 },
    hours: 'Mon-Thu 10am-8pm, Fri-Sat 9am-5pm',
    hoursEs: 'Lun-Jue 10am-8pm, Vie-Sab 9am-5pm',
    distance: 3.4,
    programs: [],
  },
  {
    id: 'loc-004',
    name: 'La Alma Recreation Center',
    nameEs: 'Centro de Recreacion La Alma',
    type: 'rec-center',
    address: '1325 W 11th Ave, Denver, CO 80204',
    neighborhood: 'La Alma/Lincoln Park',
    coordinates: { lat: 39.7344, lng: -105.0053 },
    hours: 'Mon-Fri 6am-9pm, Sat 8am-5pm',
    hoursEs: 'Lun-Vie 6am-9pm, Sab 8am-5pm',
    distance: 2.8,
    programs: [],
  },
  {
    id: 'loc-005',
    name: 'Gonzales Branch Library',
    nameEs: 'Biblioteca Sucursal Gonzales',
    type: 'library',
    address: '256 S Acoma St, Denver, CO 80223',
    neighborhood: 'Baker',
    coordinates: { lat: 39.7211, lng: -104.9983 },
    hours: 'Mon-Thu 10am-8pm, Fri-Sat 9am-5pm',
    hoursEs: 'Lun-Jue 10am-8pm, Vie-Sab 9am-5pm',
    distance: 3.9,
    programs: [],
  },
];

export const experienceVenues: ExperienceVenue[] = [
  {
    id: 'exp-001',
    name: 'Denver Zoo',
    nameEs: 'Zoologico de Denver',
    emoji: '🦁',
    address: '2300 Steele St, Denver, CO 80205',
    neighborhood: 'City Park',
    discountType: 'free',
    discountLabel: 'FREE with My Denver Card',
    discountLabelEs: 'GRATIS con Mi Tarjeta Denver',
    description: 'Explore over 4,000 animals from around the world at one of the most popular zoos in the country.',
    descriptionEs: 'Explora mas de 4,000 animales de todo el mundo en uno de los zoologicos mas populares del pais.',
  },
  {
    id: 'exp-002',
    name: 'Denver Museum of Nature & Science',
    nameEs: 'Museo de Naturaleza y Ciencia de Denver',
    emoji: '🦕',
    address: '2001 Colorado Blvd, Denver, CO 80205',
    neighborhood: 'City Park',
    discountType: 'free',
    discountLabel: 'FREE with My Denver Card',
    discountLabelEs: 'GRATIS con Mi Tarjeta Denver',
    description: 'Discover dinosaurs, space, gems, and more at this world-class science museum.',
    descriptionEs: 'Descubre dinosaurios, espacio, gemas y mas en este museo de ciencias de clase mundial.',
  },
  {
    id: 'exp-003',
    name: 'History Colorado Center',
    nameEs: 'Centro de Historia de Colorado',
    emoji: '🏛️',
    address: '1200 Broadway, Denver, CO 80203',
    neighborhood: 'Capitol Hill',
    discountType: 'free',
    discountLabel: 'FREE with My Denver Card',
    discountLabelEs: 'GRATIS con Mi Tarjeta Denver',
    description: 'Interactive exhibits bringing Colorado history to life for all ages.',
    descriptionEs: 'Exhibiciones interactivas que dan vida a la historia de Colorado para todas las edades.',
  },
  {
    id: 'exp-004',
    name: 'Denver Art Museum',
    nameEs: 'Museo de Arte de Denver',
    emoji: '🎨',
    address: '100 W 14th Ave Pkwy, Denver, CO 80204',
    neighborhood: 'Civic Center',
    discountType: 'free',
    discountLabel: 'FREE with My Denver Card',
    discountLabelEs: 'GRATIS con Mi Tarjeta Denver',
    description: 'One of the largest art museums in the West with over 70,000 works from around the world.',
    descriptionEs: 'Uno de los museos de arte mas grandes del Oeste con mas de 70,000 obras de todo el mundo.',
  },
  {
    id: 'exp-005',
    name: 'Denver Botanic Gardens',
    nameEs: 'Jardines Botanicos de Denver',
    emoji: '🌺',
    address: '1007 York St, Denver, CO 80206',
    neighborhood: 'Cheesman Park',
    discountType: 'discounted',
    discountLabel: '50% off with My Denver Card',
    discountLabelEs: '50% de descuento con Mi Tarjeta Denver',
    description: 'Beautiful gardens featuring plants from around the world and stunning seasonal displays.',
    descriptionEs: 'Hermosos jardines con plantas de todo el mundo y exhibiciones estacionales impresionantes.',
  },
  {
    id: 'exp-006',
    name: 'Butterfly Pavilion',
    nameEs: 'Pabellon de Mariposas',
    emoji: '🦋',
    address: '6252 W 104th Ave, Westminster, CO 80020',
    neighborhood: 'Westminster',
    discountType: 'discounted',
    discountLabel: '50% off with My Denver Card',
    discountLabelEs: '50% de descuento con Mi Tarjeta Denver',
    description: 'Walk among thousands of butterflies and encounter invertebrates from around the world.',
    descriptionEs: 'Camina entre miles de mariposas y encuentra invertebrados de todo el mundo.',
  },
];

export const recentCheckIns: CheckInRecord[] = [
  {
    id: 'checkin-001',
    locationId: 'loc-001',
    childId: 'child-001',
    timestamp: '2025-01-15T15:30:00',
    type: 'program-session',
  },
  {
    id: 'checkin-002',
    locationId: 'loc-001',
    childId: 'child-001',
    timestamp: '2025-01-13T15:25:00',
    type: 'program-session',
  },
];

export const schoolPrograms: SchoolProgram[] = [
  // Sofia — Denver East High School (10th grade, age 16)
  {
    id: 'school-001',
    name: 'AP Computer Science A',
    nameEs: 'AP Ciencias de la Computacion A',
    school: 'Denver East High School',
    schoolEs: 'Escuela Secundaria Denver East',
    childId: 'child-001',
    category: 'stem',
    schedule: { days: ['Monday', 'Wednesday', 'Friday'], startTime: '10:15 AM', endTime: '11:05 AM' },
    instructor: 'Mr. Patel',
    room: 'Room 214',
    spotsAvailable: 4,
    spotsTotal: 28,
    cost: 0,
    acceptedFunding: [],
    description: 'College-level computer science course covering Java programming, data structures, and algorithms. Prepares for AP exam.',
    descriptionEs: 'Curso universitario de ciencias de la computacion que cubre programacion Java, estructuras de datos y algoritmos. Prepara para el examen AP.',
  },
  {
    id: 'school-002',
    name: 'Varsity Art Studio',
    nameEs: 'Estudio de Arte Avanzado',
    school: 'Denver East High School',
    schoolEs: 'Escuela Secundaria Denver East',
    childId: 'child-001',
    category: 'arts',
    schedule: { days: ['Tuesday', 'Thursday'], startTime: '1:30 PM', endTime: '3:00 PM' },
    instructor: 'Ms. Rivera',
    room: 'Art Wing B',
    spotsAvailable: 6,
    spotsTotal: 20,
    cost: 25,
    acceptedFunding: ['fund-002'],
    description: 'Advanced studio art elective covering portfolio development, mixed media, and exhibition preparation.',
    descriptionEs: 'Electiva de arte avanzado que cubre desarrollo de portafolio, medios mixtos y preparacion de exhibiciones.',
  },
  {
    id: 'school-003',
    name: 'Student Council Leadership',
    nameEs: 'Liderazgo del Consejo Estudiantil',
    school: 'Denver East High School',
    schoolEs: 'Escuela Secundaria Denver East',
    childId: 'child-001',
    category: 'life-skills',
    schedule: { days: ['Wednesday'], startTime: '3:15 PM', endTime: '4:30 PM' },
    instructor: 'Ms. Thompson',
    room: 'Room 102',
    spotsAvailable: 2,
    spotsTotal: 15,
    cost: 0,
    acceptedFunding: [],
    description: 'Plan school events, develop leadership skills, and represent the student body. Earns volunteer credit hours.',
    descriptionEs: 'Planifica eventos escolares, desarrolla habilidades de liderazgo y representa al cuerpo estudiantil. Gana horas de credito voluntario.',
  },
  {
    id: 'school-004',
    name: 'East Angels Robotics Team',
    nameEs: 'Equipo de Robotica East Angels',
    school: 'Denver East High School',
    schoolEs: 'Escuela Secundaria Denver East',
    childId: 'child-001',
    category: 'stem',
    schedule: { days: ['Tuesday', 'Thursday'], startTime: '3:15 PM', endTime: '5:00 PM' },
    instructor: 'Mr. Chen',
    room: 'STEM Lab',
    spotsAvailable: 3,
    spotsTotal: 18,
    cost: 50,
    acceptedFunding: ['fund-002'],
    description: 'Competitive robotics team preparing for FIRST Robotics regional championship. Build, code, and compete.',
    descriptionEs: 'Equipo competitivo de robotica preparandose para el campeonato regional FIRST Robotics. Construye, programa y compite.',
  },
  // Diego — Whittier ECE-8 (2nd grade, age 7)
  {
    id: 'school-005',
    name: 'After-School Reading Club',
    nameEs: 'Club de Lectura Despues de Escuela',
    school: 'Whittier ECE-8',
    schoolEs: 'Whittier ECE-8',
    childId: 'child-002',
    category: 'academic',
    schedule: { days: ['Monday', 'Wednesday'], startTime: '3:30 PM', endTime: '4:30 PM' },
    instructor: 'Mrs. Martinez',
    room: 'Library',
    spotsAvailable: 8,
    spotsTotal: 20,
    cost: 0,
    acceptedFunding: [],
    description: 'Fun guided reading sessions with age-appropriate books, reading games, and literacy activities. Snack provided.',
    descriptionEs: 'Sesiones de lectura guiada con libros apropiados para la edad, juegos de lectura y actividades de alfabetizacion. Se proporciona merienda.',
  },
  {
    id: 'school-006',
    name: 'PE Extended: Soccer Skills',
    nameEs: 'Ed. Fisica Extendida: Habilidades de Futbol',
    school: 'Whittier ECE-8',
    schoolEs: 'Whittier ECE-8',
    childId: 'child-002',
    category: 'sports',
    schedule: { days: ['Tuesday', 'Thursday'], startTime: '3:30 PM', endTime: '4:45 PM' },
    instructor: 'Coach Daniels',
    room: 'Field / Gym',
    spotsAvailable: 10,
    spotsTotal: 24,
    cost: 30,
    acceptedFunding: ['fund-001', 'fund-003'],
    description: 'Extended PE program focused on soccer fundamentals, teamwork, and fitness. All skill levels welcome.',
    descriptionEs: 'Programa extendido de educacion fisica enfocado en fundamentos de futbol, trabajo en equipo y fitness. Todos los niveles son bienvenidos.',
  },
  {
    id: 'school-007',
    name: 'Music Discovery',
    nameEs: 'Descubrimiento Musical',
    school: 'Whittier ECE-8',
    schoolEs: 'Whittier ECE-8',
    childId: 'child-002',
    category: 'music',
    schedule: { days: ['Friday'], startTime: '3:30 PM', endTime: '4:30 PM' },
    instructor: 'Mr. Owens',
    room: 'Music Room',
    spotsAvailable: 5,
    spotsTotal: 16,
    cost: 0,
    acceptedFunding: [],
    description: 'Introduction to rhythm, melody, and instruments. Kids explore drums, xylophone, recorder, and singing.',
    descriptionEs: 'Introduccion al ritmo, melodia e instrumentos. Los ninos exploran tambores, xilofono, flauta y canto.',
  },
  {
    id: 'school-008',
    name: 'Science Explorers Club',
    nameEs: 'Club de Exploradores de Ciencias',
    school: 'Whittier ECE-8',
    schoolEs: 'Whittier ECE-8',
    childId: 'child-002',
    category: 'stem',
    schedule: { days: ['Wednesday'], startTime: '3:30 PM', endTime: '4:45 PM' },
    instructor: 'Ms. Kim',
    room: 'Science Lab',
    spotsAvailable: 6,
    spotsTotal: 18,
    cost: 15,
    acceptedFunding: ['fund-002', 'fund-003'],
    description: 'Hands-on science experiments and STEM projects. Topics include volcanoes, magnets, simple machines, and nature.',
    descriptionEs: 'Experimentos de ciencia y proyectos STEM practicos. Temas incluyen volcanes, imanes, maquinas simples y naturaleza.',
  },
];
